## !! Generated by cmake.  Do not edit.
## Makevars for ib
#
# SRC_DIR          = @SRC_DIR@
# BUILD_DIR        = @BUILD_DIR@
# R_PKG_DIR        = @R_PKG_DIR@
# R_LIBS           = @R_LIBS@

# CXX flags for locating headers and libs
PKG_CPPFLAGS = \
-I@IBAPI_ROOT@ \
-I@SRC_DIR@ \
-I@SRC_DIR@/ib/@IBAPI_IMPL_DIR@ \
-DR_EXTENSION

## Use the R_HOME indirection to support installations of multiple R version
PKG_LIBS = \
`$(R_HOME)/bin/Rscript -e "Rcpp:::LdFlags()"` \
-L@SRC_DIR@/ib -lapi_base \
-L@SRC_DIR@/ib/@IBAPI_IMPL_DIR@ -lib_api \
-L@SRC_DIR@/zmq -lzmq_components \
-L@SRC_DIR@/proto -lproto_components \
-lprotobuf-lite \
-lzmq \
-lgflags -lglog





